# ***********************
# 적용실패함 : jar->war 파일로 변경시도, 라이브러리 충돌 발생

# 실행 명령어 
## $ docker build --build-arg jarfile=test-0.0.1-SNAPSHOT.jar
## $ docker build -f Dockerfile.dev -t tomcat9-app-war:v20260105-01 .
## $ docker build -f Dockerfile.dev -t tomcat9-app-war:v20260105-02 .

#############################################
# 1단계 maven 빌드
# ...

#############################################
# 2단계 톰캣 이미지 생성
# 빌드시 넘어올 수 있는 인자 설정
ARG jarfile

# 기본 이미지 지정
FROM tomcat:9.0

# 라벨 설정
LABEL project_name=jpawithmybits_프로젝트
LABEL version="1.0"

# 컨테이너가 리스닝할 포트 및 프로토콜 설정
EXPOSE 8080

# 기본 제공되는 예제 앱 제거 (보안 및 경로 깔끔화)
RUN rm -rf /usr/local/tomcat/webapps/*

# 이미지의 파일 시스템에 추가함.
ADD ./target/sht_webapp.war /usr/local/tomcat/webapps/ROOT.war

# 컨테이너 실행시 톰캣 실행 -> docker 명령어 실행시 변경 가능
CMD ["catalina.sh", "run"]




# 컨테이너 실행시 톰캣 실행(변경불가)
# ENTRYPOINT ["catalina.sh","run"]
# 볼륨 마운트
# VOLUME <경로>




